// <auto-generated />
using System;
using EntityFramework_Playground.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFramework_Playground.Migrations
{
    [DbContext(typeof(ZooContext))]
    [Migration("20221101115114_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("EntityFramework_Playground.Infrastructure.AnimalSnapshot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CageSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CageSnapshotId");

                    b.ToTable("AnimalSnapshot");
                });

            modelBuilder.Entity("EntityFramework_Playground.Infrastructure.CageSnapshot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnimalSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OccupiedSlots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Slots")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZooSnapshotId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ZooSnapshotId");

                    b.ToTable("CageSnapshot");
                });

            modelBuilder.Entity("EntityFramework_Playground.Infrastructure.ZooSnapshot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("zoo");
                });

            modelBuilder.Entity("EntityFramework_Playground.Infrastructure.AnimalSnapshot", b =>
                {
                    b.HasOne("EntityFramework_Playground.Infrastructure.CageSnapshot", null)
                        .WithMany("Residents")
                        .HasForeignKey("CageSnapshotId");
                });

            modelBuilder.Entity("EntityFramework_Playground.Infrastructure.CageSnapshot", b =>
                {
                    b.HasOne("EntityFramework_Playground.Infrastructure.ZooSnapshot", null)
                        .WithMany("Cages")
                        .HasForeignKey("ZooSnapshotId");
                });

            modelBuilder.Entity("EntityFramework_Playground.Infrastructure.CageSnapshot", b =>
                {
                    b.Navigation("Residents");
                });

            modelBuilder.Entity("EntityFramework_Playground.Infrastructure.ZooSnapshot", b =>
                {
                    b.Navigation("Cages");
                });
#pragma warning restore 612, 618
        }
    }
}
